# Generated by Django 4.0 on 2022-01-01 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=1000)),
                ('Completed', models.BooleanField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CompletedOn', models.DateTimeField()),
                ('BelongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_api.user')),
            ],
        ),
    ]
