# Generated by Django 4.0 on 2022-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_rename_name_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='CompletedOn',
            field=models.DateTimeField(null=True),
        ),
    ]
