# Generated by Django 4.0 on 2022-01-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todo_api', '0003_alter_task_completedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='BelongsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
